site_name: Dr. Everitt's Neighborhood
site_url: https://wiki.hkn.illinois.edu
theme:
  name: material
  palette:
    primary: custom
    accent: custom
    typeset: custom
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
  custom_dir: overrides
  static_templates:
    - 404.html
extra_css:
  - styles/theme.css
extra:
  generator: false
  analytics:
    provider: google
    property: G-01G0XDGEP8
plugins:
  - search
  - bettertags:
      indexes:
        "Proficiency Exams/index.md": "*subfolder"
        "Course Wiki/index.md": "*subfolder"
        "Example Schedules/index.md": "*subfolder"
      tags_allowed:
        - Circuits
        - Integrated circuits
        - Analog circuits
        - Digital circuits

        - Electromagnetics
        - Radio frequency
        - Optics
        - Antennas
        - Remote sensing

        - Microelectronics
        - Semiconductor devices
        - Semiconductor processing
        - Computational electronics

        - Power
        - Power systems
        - Electric machines
        - Power electronics

        - Communications

        - Control systems

        - Signal processing
        - Digital signal processing
        - Image processing

        - Computer architecture
        - Computer systems
        - Embedded systems
        - Operating systems
        - Software

        - Robotics
        - Artificial intelligence
        - Machine learning

        - Random processes
        - Algorithms

        - Research
        - Senior design

        - Discrete math
        - Data structures

        - Calculus
        - Differential equations
        - Linear algebra
        - Analysis

        - Classical mechanics
        - Thermodynamics
        - Statistical mechanics
        - Quantum mechanics
        - Relativity

  - git-revision-date-localized
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_static_files"
  - redirects:
      redirect_maps:
        "Course Wiki/CS Course Offerings/CS483.md": "Course Wiki/ECE Course Offerings/ECE408.md"
markdown_extensions:
  - footnotes