site_name: Dr. Everitt's Neighborhood
site_url: https://wiki.hkn.illinois.edu
theme:
  name: material
  palette:
    primary: custom
    accent: custom
    typeset: custom
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
  custom_dir: overrides
  static_templates:
    - 404.html
extra_css:
  - styles/theme.css
extra:
  generator: false
  analytics:
    provider: google
    property: G-01G0XDGEP8
plugins:
  - search
  - bettertags:
      indexes:
        "Proficiency Exams/index.md": "*subfolder"
        "Course Wiki/index.md": "*subfolder"
        "Example Schedules/index.md": "*subfolder"
      tags_allowed:
        - Circuits
        - Analog circuits
        - Digital circuits
        - Electromagnetics
        - Computer architecture
        - Digital design
        - Signal processing
        - Communications
        - Computer systems
        - Software
        - Digital signal processing
        - Image processing
        - Random processes
        - Radio frequency
        - Remote sensing
        - Optics
        - Power
        - Power systems
        - Electric machines
        - Circuits
        - Renewable energy
        - Power electronics
        - Semiconductors
        - Semiconductor fabrication
        - Microelectronics
        - Photonics
        - Integrated circuits
        - Antennas
        - Algorithms
        - Hardware
        - Computer systems
        - Embedded systems
        - Operating systems
        - Semiconductor modeling
        - Control systems
        - Research
        - Senior design
        - Data structures
        - Discrete math
        - Calculus
        - Differential equations
        - Linear algebra
        - Analysis
        - Mechanics
        - Thermodynamics
        - Statistical mechanics
        - Relativity
        - Quantum mechanics
        - Robotics
  - git-revision-date-localized
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_static_files"
  - redirects:
      redirect_maps:
        "Course Wiki/CS Course Offerings/CS483.md": "Course Wiki/ECE Course Offerings/ECE408.md"
markdown_extensions:
  - footnotes