site_name: Dr. Everitt's Neighborhood
site_url: https://wiki.hkn.illinois.edu
theme:
  name: material
  palette:
    primary: custom
    accent: custom
    typeset: custom
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
  custom_dir: overrides
  static_templates:
    - 404.html
extra_css:
  - styles/theme.css
extra:
  generator: false
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_static_files"
  - redirects:
      redirect_maps:
