name: Auto-approve small changes
on: pull_request
env:
  MAX_CHANGED: 40
jobs:
  decision:
    runs-on: ubuntu-latest
    outputs:
      approve: ${{steps.decide.outputs.approve}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: sudo apt install zsh
      - id: decide
        run: zsh ./autoapprove.zsh
  auto-approve:
    runs-on: ubuntu-latest
    needs: decision
    permissions:
      pull-requests: write
    if: ${{needs.decision.outputs.approve}} == true
    steps:
      - uses: hmarr/auto-approve-action@v3
      
